version: '3.8'

services:
  backend:
    # Notice we removed "build: context: ./backend"
    image: kushalshr0609/arcade-backend:latest
    ports:
      - "8000:8000"

  frontend:
    # Notice we removed "build: context: ./frontend"
    image: kushalshr0609/arcade-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
